"""This module is used to gather all constants and magic number used in the Novu client."""

CHANGES_ENDPOINT = "/v1/changes"
EVENTS_ENDPOINT = "/v1/events/trigger"
EXECUTION_DETAILS_ENDPOINT = "/v1/execution-details"
FEEDS_ENDPOINT = "/v1/feeds"
INTEGRATIONS_ENDPOINT = "/v1/integrations"
LAYOUTS_ENDPOINT = "/v1/layouts"
MESSAGES_ENDPOINT = "/v1/messages"
NOTIFICATION_GROUPS_ENDPOINT = "/v1/notification-groups"
NOTIFICATION_TEMPLATES_ENDPOINT = "/v1/notification-templates"
SUBSCRIBERS_ENDPOINT = "/v1/subscribers"
TOPICS_ENDPOINT = "/v1/topics"

DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%f%z"
