name: Semver to tag new version

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  semver:
    runs-on: ubuntu-latest
    if: | # Only trigger this job on manual trigger from alpha/beta or on main.
      (
        github.event_name == 'workflow_dispatch' &&
        (github.ref == 'refs/heads/alpha' || github.ref == 'refs/heads/beta')
      ) ||
      github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic Release - prepare
        run: |
          cat <<EOF > package.json
          {
            "name": "semver",
            "private": true
          }
          EOF

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/changelog@6.0.2
            @google/semantic-release-replace-plugin@1.2.0
            @semantic-release/git@10.0.1
            @semantic-release/github@8.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT }}
        id: semantic

    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_channel: ${{ steps.semantic.outputs.new_release_channel }}
