name: Semver to tag new version

on:
  push:
    branches: [main, alpha, beta]

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_BOT }}
      - name: Semantic Release - prepare
        run: |
          cat <<EOF > package.json
          {
            "name": "semver",
            "private": true
          }
          EOF
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/changelog@6.0.2
            @google/semantic-release-replace-plugin@1.2.0
            @semantic-release/git@10.0.1
            @semantic-release/github@8.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: semantic
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_channel: ${{ steps.semantic.outputs.new_release_channel }}
